Github action with release artefact upload.

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -13,19 +13,20 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v4
+    - uses: actions/checkout@v6
       with:
         fetch-depth: 0
     
     - name: set-env
       shell: bash
       run: |
-        VERSION=$(git describe --tags --dirty --abbrev=0 2>/dev/null || echo "untagged-${GITHUB_SHA::7}")
+        VERSION=$(git describe --tags --dirty 2>/dev/null)
+        TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "untagged-${GITHUB_SHA::7}")
         BRANCH=$(git branch --show-current)
         echo "VERSION=$VERSION" >> "$GITHUB_ENV"
-        echo "FILE_VERSION=$BRANCH-$VERSION" >> "$GITHUB_ENV"
+        echo "FILE_VERSION=$BRANCH-$TAG" >> "$GITHUB_ENV"
         git status
-        git describe --tags --dirty --abbrev=0 || echo "describe failed"
+        git describe --tags --dirty || echo "describe failed"
 
     - name: Build 
       # Use a bash shell so we can use the same syntax for environment variable
@@ -38,7 +39,7 @@ jobs:
 
       run: |
         docker run --rm -v ${{ github.workspace }}:/project -w /project espressif/idf:release-v5.4 \
-        bash -c ". \$IDF_PATH/export.sh && idf.py -DFW_VERSION=\"${VERSION}\" -DCMAKE_BUILD_TYPE=Release -D SDKCONFIG_DEFAULTS=\"sdkconfig.defaults;sdkconfig.defaults.release\" build"
+        bash -c ". \$IDF_PATH/export.sh && idf.py -DFW_VERSION=\"${{ env.VERSION }}\" -DCMAKE_BUILD_TYPE=Release -D SDKCONFIG_DEFAULTS=\"sdkconfig.defaults;sdkconfig.defaults.release\" build"
             
         echo "--- Inhalt von build/ nach Build ---"
         ls -lh build/
@@ -56,5 +57,15 @@ jobs:
       with:
         name: XCVarioPur-${{ env.FILE_VERSION }}
         path: artifacts/*
+
+    - name: Publish Release
+      if: startsWith(github.ref, 'refs/tags/')
+      uses: ncipollo/release-action@v1
+      with:
+        artifacts: "artifacts/*.bin,artifacts/*.elf.gz"
+        allowUpdates: true
+        artifactErrorsFailBuild: true
+        generateReleaseNotes: true
+        replacesArtifacts: true
 
 
